[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "alloc"]

[target.'cfg(any(target_arch = "x86_64", target_arch = "aarch64", target_arch = "riscv64"))']
rustflags = [
  "-C", "relocation-model=pic",
  "-C", "link-arg=-Tkernel/link.ld",
  "-C", "link-arg=-pie"
]