[package]
name = "unix-v11-kernel"
version = "0.0.1"
edition = "2021"

[dependencies]
aarch64 = "0.0.13"
linked_list_allocator = "0.10.5"
x86_64 = "0.15.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
